version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bhusawal_basket_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Carlos@777
      POSTGRES_DB: bhusawal_basket
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
